package net.vulkanmod.render.chunk;

import net.vulkanmod.Initializer;
import net.vulkanmod.render.vertex.TerrainRenderType;
import net.vulkanmod.vulkan.Device;
import net.vulkanmod.vulkan.Synchronization;
import net.vulkanmod.vulkan.Vulkan;
import net.vulkanmod.vulkan.memory.MemoryManager;
import net.vulkanmod.vulkan.queue.CommandPool;
import net.vulkanmod.vulkan.queue.Queue;
import net.vulkanmod.vulkan.queue.TransferQueue;
import net.vulkanmod.vulkan.shader.SPIRVUtils;
import org.lwjgl.system.MemoryStack;
import org.lwjgl.vulkan.VkBufferMemoryBarrier;
import org.lwjgl.vulkan.VkComputePipelineCreateInfo;
import org.lwjgl.vulkan.VkDescriptorBufferInfo;
import org.lwjgl.vulkan.VkDescriptorPoolCreateInfo;
import org.lwjgl.vulkan.VkDescriptorPoolSize;
import org.lwjgl.vulkan.VkDescriptorSetAllocateInfo;
import org.lwjgl.vulkan.VkDescriptorSetLayoutBinding;
import org.lwjgl.vulkan.VkDescriptorSetLayoutCreateInfo;
import org.lwjgl.vulkan.VkPipelineLayoutCreateInfo;
import org.lwjgl.vulkan.VkPipelineShaderStageCreateInfo;
import org.lwjgl.vulkan.VkPushConstantRange;
import org.lwjgl.vulkan.VkQueueFamilyProperties;
import org.lwjgl.vulkan.VkShaderModuleCreateInfo;
import org.lwjgl.vulkan.VkWriteDescriptorSet;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.IntBuffer;
import java.nio.LongBuffer;

import static org.lwjgl.vulkan.VK10.*;

/**
 * CI-only proof that a bounded GPU terrain reservation can be written by compute
 * in-place inside the persistent area vertex buffer.
 *
 * <p>This does not generate or draw production terrain. It isolates the output-side
 * Vulkan contract needed by the mesher: non-zero suballocation addressing, storage
 * writes, old-vertex/transfer to compute ordering, compute to transfer/vertex-input
 * visibility, and exact readback without growing the area buffer.</p>
 */
public final class GpuTerrainOutputComputeSmokeTest {
    private static final int WORDS_PER_FACE = GpuTerrainOutputStore.BYTES_PER_FACE / Integer.BYTES;
    private static final int BYTES_PER_FACE = GpuTerrainOutputStore.BYTES_PER_FACE;
    private static final int PUSH_CONSTANT_BYTES = 3 * Integer.BYTES;
    private static final int SEED = 0x4f555431; // OUT1

    private GpuTerrainOutputComputeSmokeTest() {}

    public static void verify() {
        DrawBuffers drawBuffers = new DrawBuffers();
        GpuTerrainOutputStore store = null;
        try {
            drawBuffers.allocateBuffers();
            int initialCapacity = drawBuffers.vertexBuffer.getCapacityBytes();
            store = new GpuTerrainOutputStore(drawBuffers);

            // Keep one live reservation in front of the target so the shader must
            // honor a real non-zero AreaBuffer byte base instead of accidentally
            // succeeding only at buffer offset zero.
            var guard = requireReservation(store.reserve(0, TerrainRenderType.SOLID, 1L, 1),
                    "GPU terrain output compute guard reservation must fit");
            require(store.publish(guard, 1, false),
                    "GPU terrain output compute guard must publish");

            var reservation = requireReservation(store.reserve(
                            1, TerrainRenderType.SOLID, 1L, 1),
                    "GPU terrain output compute reservation must fit");
            GpuTerrainOutputStore.Target target;
            int[] actual;

            // AreaBuffer uploads/growth synchronize on this same monitor. Resolve the
            // current VkBuffer and submit the helper compute while holding it, so a
            // concurrent grow cannot replace/free the target between lookup and queue
            // submission. Once submitted, any later growth copy is ordered after this
            // write on the graphics queue and can copy the generated bytes safely.
            synchronized(drawBuffers.vertexBuffer) {
                target = store.target(reservation);
                require(target != null && target.bufferId() != 0L,
                        "GPU terrain output compute target must resolve a live VkBuffer");
                require(target.byteOffset() >= BYTES_PER_FACE
                                && target.byteOffset() % GpuTerrainOutputStore.VERTEX_BYTES == 0,
                        "GPU terrain output compute target must use a non-zero vertex-aligned suballocation");
                require(target.byteCapacity() == BYTES_PER_FACE,
                        "GPU terrain output compute smoke expects exactly one face reservation");
                try(Probe probe = new Probe()) {
                    actual = probe.dispatch(target);
                }
            }

            require(actual.length == WORDS_PER_FACE,
                    "GPU terrain output compute readback word count mismatch");
            for(int word = 0; word < actual.length; ++word) {
                int expected = expectedWord(word);
                if(actual[word] != expected) {
                    throw new AssertionError("GPU terrain output compute mismatch at word "
                            + word + ": expected=" + expected + " actual=" + actual[word]);
                }
            }

            require(store.publish(reservation, 1, false),
                    "Exact compute-written GPU terrain output must publish");
            var resident = store.getResidency(1, TerrainRenderType.SOLID);
            require(resident.valid() && resident.generation() == 1L
                            && resident.faceCount() == 1
                            && resident.byteOffset() == target.byteOffset(),
                    "Compute-written GPU terrain output residency mismatch");
            require(drawBuffers.vertexBuffer.getCapacityBytes() == initialCapacity,
                    "Compute-written GPU terrain output must not grow the area buffer");

            Initializer.LOGGER.info(
                    "VULKANMOD_GPU_TERRAIN_OUTPUT_COMPUTE_OK: exact non-zero suballocation storage write, compute-to-transfer/vertex visibility, bounded no-growth residency");
        } finally {
            Vulkan.waitIdle();
            if(store != null)
                store.close();
            drawBuffers.releaseBuffers();
        }
    }

    private static int expectedWord(int word) {
        return SEED ^ (word * 0x9e3779b9);
    }

    private static GpuTerrainOutputStore.Reservation requireReservation(
            GpuTerrainOutputStore.Reservation reservation, String message) {
        if(reservation == null)
            throw new AssertionError(message);
        return reservation;
    }

    private static void require(boolean condition, String message) {
        if(!condition)
            throw new AssertionError(message);
    }

    private static final class Probe implements AutoCloseable {
        private long descriptorSetLayout;
        private long descriptorPool;
        private long descriptorSet;
        private long pipelineLayout;
        private long pipeline;
        private boolean closed;

        Probe() {
            if(!graphicsQueueSupportsCompute())
                throw new UnsupportedOperationException(
                        "Graphics queue family does not support compute dispatch");
            createDescriptorResources();
            createPipelineLayout();
            createPipeline();
        }

        int[] dispatch(GpuTerrainOutputStore.Target target) {
            if(closed)
                throw new IllegalStateException("GPU terrain output compute probe is closed");
            if(target == null || target.bufferId() == 0L
                    || target.byteOffset() < 0 || (target.byteOffset() & 3) != 0
                    || target.byteCapacity() != BYTES_PER_FACE)
                throw new IllegalArgumentException("Invalid GPU terrain output compute target");

            long readbackBuffer = VK_NULL_HANDLE;
            long readbackAllocation = VK_NULL_HANDLE;
            try(MemoryStack stack = MemoryStack.stackPush()) {
                LongBuffer pReadbackBuffer = stack.mallocLong(1);
                var pReadbackAllocation = stack.mallocPointer(1);
                MemoryManager memoryManager = MemoryManager.getInstance();
                memoryManager.createBuffer(BYTES_PER_FACE, VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                        pReadbackBuffer, pReadbackAllocation);
                readbackBuffer = pReadbackBuffer.get(0);
                readbackAllocation = pReadbackAllocation.get(0);

                updateDescriptorSet(target.bufferId());

                CommandPool.CommandBuffer commandBuffer = Device.getGraphicsQueue().beginCommands();
                barrierPreviousConsumersToCompute(commandBuffer, target);

                vkCmdBindPipeline(commandBuffer.getHandle(),
                        VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
                vkCmdBindDescriptorSets(commandBuffer.getHandle(),
                        VK_PIPELINE_BIND_POINT_COMPUTE, pipelineLayout, 0,
                        stack.longs(descriptorSet), null);
                ByteBuffer push = stack.malloc(PUSH_CONSTANT_BYTES).order(ByteOrder.nativeOrder());
                push.putInt(0, target.byteOffset() / Integer.BYTES);
                push.putInt(Integer.BYTES, WORDS_PER_FACE);
                push.putInt(2 * Integer.BYTES, SEED);
                vkCmdPushConstants(commandBuffer.getHandle(), pipelineLayout,
                        VK_SHADER_STAGE_COMPUTE_BIT, 0, push);
                vkCmdDispatch(commandBuffer.getHandle(), 1, 1, 1);

                barrierComputeWritesToConsumers(commandBuffer, target);
                TransferQueue.uploadBufferCmd(commandBuffer,
                        target.bufferId(), target.byteOffset(),
                        readbackBuffer, 0L, BYTES_PER_FACE);

                Device.getGraphicsQueue().submitCommands(commandBuffer);
                Synchronization.waitFence(commandBuffer.getFence());
                Synchronization.INSTANCE.retireSameQueueCommandBufferAfterFence(commandBuffer);

                int[] result = new int[WORDS_PER_FACE];
                long allocation = readbackAllocation;
                memoryManager.MapAndCopy(allocation, BYTES_PER_FACE, pointer -> {
                    ByteBuffer bytes = pointer.getByteBuffer(0, BYTES_PER_FACE)
                            .order(ByteOrder.nativeOrder());
                    for(int i = 0; i < result.length; ++i)
                        result[i] = bytes.getInt(i * Integer.BYTES);
                });
                return result;
            } finally {
                if(readbackBuffer != VK_NULL_HANDLE)
                    MemoryManager.freeBuffer(readbackBuffer, readbackAllocation);
            }
        }

        private void createDescriptorResources() {
            try(MemoryStack stack = MemoryStack.stackPush()) {
                VkDescriptorSetLayoutBinding.Buffer bindings =
                        VkDescriptorSetLayoutBinding.calloc(1, stack);
                bindings.get(0)
                        .binding(0)
                        .descriptorType(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER)
                        .descriptorCount(1)
                        .stageFlags(VK_SHADER_STAGE_COMPUTE_BIT)
                        .pImmutableSamplers(null);

                VkDescriptorSetLayoutCreateInfo layoutInfo =
                        VkDescriptorSetLayoutCreateInfo.calloc(stack)
                                .sType$Default()
                                .pBindings(bindings);
                LongBuffer pLayout = stack.mallocLong(1);
                check(vkCreateDescriptorSetLayout(Device.device, layoutInfo, null, pLayout),
                        "create GPU terrain output compute descriptor set layout");
                descriptorSetLayout = pLayout.get(0);

                VkDescriptorPoolSize.Buffer poolSizes = VkDescriptorPoolSize.calloc(1, stack);
                poolSizes.get(0)
                        .type(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER)
                        .descriptorCount(1);
                VkDescriptorPoolCreateInfo poolInfo = VkDescriptorPoolCreateInfo.calloc(stack)
                        .sType$Default()
                        .pPoolSizes(poolSizes)
                        .maxSets(1);
                LongBuffer pPool = stack.mallocLong(1);
                check(vkCreateDescriptorPool(Device.device, poolInfo, null, pPool),
                        "create GPU terrain output compute descriptor pool");
                descriptorPool = pPool.get(0);

                VkDescriptorSetAllocateInfo allocateInfo = VkDescriptorSetAllocateInfo.calloc(stack)
                        .sType$Default()
                        .descriptorPool(descriptorPool)
                        .pSetLayouts(stack.longs(descriptorSetLayout));
                LongBuffer pSet = stack.mallocLong(1);
                check(vkAllocateDescriptorSets(Device.device, allocateInfo, pSet),
                        "allocate GPU terrain output compute descriptor set");
                descriptorSet = pSet.get(0);
            }
        }

        private void createPipelineLayout() {
            try(MemoryStack stack = MemoryStack.stackPush()) {
                VkPushConstantRange.Buffer pushRange = VkPushConstantRange.calloc(1, stack);
                pushRange.get(0)
                        .stageFlags(VK_SHADER_STAGE_COMPUTE_BIT)
                        .offset(0)
                        .size(PUSH_CONSTANT_BYTES);
                VkPipelineLayoutCreateInfo layoutInfo = VkPipelineLayoutCreateInfo.calloc(stack)
                        .sType$Default()
                        .pSetLayouts(stack.longs(descriptorSetLayout))
                        .pPushConstantRanges(pushRange);
                LongBuffer pLayout = stack.mallocLong(1);
                check(vkCreatePipelineLayout(Device.device, layoutInfo, null, pLayout),
                        "create GPU terrain output compute pipeline layout");
                pipelineLayout = pLayout.get(0);
            }
        }

        private void createPipeline() {
            SPIRVUtils.SPIRV spirv = SPIRVUtils.compileShaderResource(
                    "/assets/vulkanmod/shaders/terrain/terrain_output_probe.comp",
                    SPIRVUtils.ShaderKind.COMPUTE_SHADER);
            long shaderModule = VK_NULL_HANDLE;
            try(MemoryStack stack = MemoryStack.stackPush()) {
                VkShaderModuleCreateInfo moduleInfo = VkShaderModuleCreateInfo.calloc(stack)
                        .sType$Default()
                        .pCode(spirv.bytecode());
                LongBuffer pModule = stack.mallocLong(1);
                check(vkCreateShaderModule(Device.device, moduleInfo, null, pModule),
                        "create GPU terrain output compute shader module");
                shaderModule = pModule.get(0);

                VkPipelineShaderStageCreateInfo stageInfo =
                        VkPipelineShaderStageCreateInfo.calloc(stack)
                                .sType$Default()
                                .stage(VK_SHADER_STAGE_COMPUTE_BIT)
                                .module(shaderModule)
                                .pName(stack.UTF8("main"));
                VkComputePipelineCreateInfo.Buffer pipelineInfo =
                        VkComputePipelineCreateInfo.calloc(1, stack);
                pipelineInfo.get(0)
                        .sType$Default()
                        .stage(stageInfo)
                        .layout(pipelineLayout)
                        .basePipelineHandle(VK_NULL_HANDLE)
                        .basePipelineIndex(-1);
                LongBuffer pPipeline = stack.mallocLong(1);
                check(vkCreateComputePipelines(Device.device, VK_NULL_HANDLE,
                                pipelineInfo, null, pPipeline),
                        "create GPU terrain output compute pipeline");
                pipeline = pPipeline.get(0);
            } finally {
                if(shaderModule != VK_NULL_HANDLE)
                    vkDestroyShaderModule(Device.device, shaderModule, null);
                spirv.free();
            }
        }

        private void updateDescriptorSet(long bufferId) {
            try(MemoryStack stack = MemoryStack.stackPush()) {
                VkDescriptorBufferInfo.Buffer bufferInfo = VkDescriptorBufferInfo.calloc(1, stack);
                bufferInfo.get(0)
                        .buffer(bufferId)
                        .offset(0L)
                        .range(VK_WHOLE_SIZE);
                VkWriteDescriptorSet.Buffer writes = VkWriteDescriptorSet.calloc(1, stack);
                writes.get(0)
                        .sType$Default()
                        .dstSet(descriptorSet)
                        .dstBinding(0)
                        .dstArrayElement(0)
                        .descriptorType(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER)
                        .descriptorCount(1)
                        .pBufferInfo(bufferInfo);
                vkUpdateDescriptorSets(Device.device, writes, null);
            }
        }

        private static void barrierPreviousConsumersToCompute(
                CommandPool.CommandBuffer commandBuffer,
                GpuTerrainOutputStore.Target target) {
            try(MemoryStack stack = MemoryStack.stackPush()) {
                VkBufferMemoryBarrier.Buffer barrier = VkBufferMemoryBarrier.calloc(1, stack);
                barrier.get(0)
                        .sType$Default()
                        .srcAccessMask(VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT
                                | VK_ACCESS_TRANSFER_READ_BIT
                                | VK_ACCESS_TRANSFER_WRITE_BIT
                                | VK_ACCESS_SHADER_WRITE_BIT)
                        .dstAccessMask(VK_ACCESS_SHADER_WRITE_BIT)
                        .srcQueueFamilyIndex(VK_QUEUE_FAMILY_IGNORED)
                        .dstQueueFamilyIndex(VK_QUEUE_FAMILY_IGNORED)
                        .buffer(target.bufferId())
                        .offset(target.byteOffset())
                        .size(target.byteCapacity());
                vkCmdPipelineBarrier(commandBuffer.getHandle(),
                        VK_PIPELINE_STAGE_VERTEX_INPUT_BIT
                                | VK_PIPELINE_STAGE_TRANSFER_BIT
                                | VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                        0, null, barrier, null);
            }
        }

        private static void barrierComputeWritesToConsumers(
                CommandPool.CommandBuffer commandBuffer,
                GpuTerrainOutputStore.Target target) {
            try(MemoryStack stack = MemoryStack.stackPush()) {
                VkBufferMemoryBarrier.Buffer barrier = VkBufferMemoryBarrier.calloc(1, stack);
                barrier.get(0)
                        .sType$Default()
                        .srcAccessMask(VK_ACCESS_SHADER_WRITE_BIT)
                        .dstAccessMask(VK_ACCESS_TRANSFER_READ_BIT
                                | VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT)
                        .srcQueueFamilyIndex(VK_QUEUE_FAMILY_IGNORED)
                        .dstQueueFamilyIndex(VK_QUEUE_FAMILY_IGNORED)
                        .buffer(target.bufferId())
                        .offset(target.byteOffset())
                        .size(target.byteCapacity());
                vkCmdPipelineBarrier(commandBuffer.getHandle(),
                        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                        VK_PIPELINE_STAGE_TRANSFER_BIT | VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,
                        0, null, barrier, null);
            }
        }

        private static boolean graphicsQueueSupportsCompute() {
            try(MemoryStack stack = MemoryStack.stackPush()) {
                IntBuffer count = stack.ints(0);
                vkGetPhysicalDeviceQueueFamilyProperties(Device.physicalDevice, count, null);
                VkQueueFamilyProperties.Buffer properties =
                        VkQueueFamilyProperties.malloc(count.get(0), stack);
                vkGetPhysicalDeviceQueueFamilyProperties(Device.physicalDevice, count, properties);
                int graphicsFamily = Queue.getQueueFamilies().graphicsFamily;
                return (properties.get(graphicsFamily).queueFlags() & VK_QUEUE_COMPUTE_BIT) != 0;
            }
        }

        private static void check(int result, String action) {
            if(result != VK_SUCCESS)
                throw new RuntimeException("Failed to " + action + ": " + result);
        }

        @Override
        public void close() {
            if(closed)
                return;
            closed = true;
            if(pipeline != VK_NULL_HANDLE)
                vkDestroyPipeline(Device.device, pipeline, null);
            if(pipelineLayout != VK_NULL_HANDLE)
                vkDestroyPipelineLayout(Device.device, pipelineLayout, null);
            if(descriptorPool != VK_NULL_HANDLE)
                vkDestroyDescriptorPool(Device.device, descriptorPool, null);
            if(descriptorSetLayout != VK_NULL_HANDLE)
                vkDestroyDescriptorSetLayout(Device.device, descriptorSetLayout, null);
        }
    }
}
